- name: Install Docker on EC2
  hosts: ec2
  become: yes
  tasks:
    - name: Copy archivo shell
      copy:
        src: /home/<user>/minikube.sh
        dest: /home/ec2-user/minikube.sh
        mode: 0755
    - name: Run shell script
      shell: /home/ec2-user/minikube.sh
