name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        

    - name: 'Initialize Terraform'
      run: terraform init

    - name: 'Plan Terraform'
      run: cd 'AWS/aws-project/Deploy a Web App on Nginx Server using AWS App Runner/nginx-web-app/terraform'
        terraform plan -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" -out=tfplan
